import type { Metadata } from "next";
import "@/app/(pages)/globals.css";
import { Noto_Sans } from 'next/font/google'
import AuthProvider from "@/context/AuthProvider";

const noto_sans = Noto_Sans({
    subsets: ['latin'],
    weight: ['400', '700']
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="!scroll-smooth">
            <AuthProvider>
                <body className={`flex flex-col h-screen ${noto_sans.className}`}>
                    <main className="flex-1">{children}</main>
                </body>
            </AuthProvider>
        </html>
    );
}

