import type { Metadata } from "next";
import "@/app/(pages)/globals.css";
import NavbarAdmin from "@/app/(components)/NavbarAdmin";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <NavbarAdmin />
                {children}
            </body>
        </html>
    );
}

