import type { Metadata } from "next";
import "@/app/(pages)/globals.css";
import NavbarAdmin from "@/app/(components)/NavbarAdmin";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="flex flex-col h-screen overflow-x-hidden bg-slate-800 lg:flex-row-reverse">
            <main className="h-[91%] lg:h-full lg:flex-1">{children}</main>
            <NavbarAdmin className="lg:w-auto" />
        </div>
    )
}

